//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiveLab.ZM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color RtGrp_BackColor {
            get {
                return ((global::System.Drawing.Color)(this["RtGrp_BackColor"]));
            }
            set {
                this["RtGrp_BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumBlue")]
        public global::System.Drawing.Color RtGrp_Plot1_Color {
            get {
                return ((global::System.Drawing.Color)(this["RtGrp_Plot1_Color"]));
            }
            set {
                this["RtGrp_Plot1_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color RtGrp_Plot2_Color {
            get {
                return ((global::System.Drawing.Color)(this["RtGrp_Plot2_Color"]));
            }
            set {
                this["RtGrp_Plot2_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RtGrp_Plot_ViewLine {
            get {
                return ((bool)(this["RtGrp_Plot_ViewLine"]));
            }
            set {
                this["RtGrp_Plot_ViewLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RtGrp_Plot_ViewPoint {
            get {
                return ((bool)(this["RtGrp_Plot_ViewPoint"]));
            }
            set {
                this["RtGrp_Plot_ViewPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color NiGrp_Backcolor {
            get {
                return ((global::System.Drawing.Color)(this["NiGrp_Backcolor"]));
            }
            set {
                this["NiGrp_Backcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color NiGrp_Plot1_color {
            get {
                return ((global::System.Drawing.Color)(this["NiGrp_Plot1_color"]));
            }
            set {
                this["NiGrp_Plot1_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color BdGrp_Plot1_color {
            get {
                return ((global::System.Drawing.Color)(this["BdGrp_Plot1_color"]));
            }
            set {
                this["BdGrp_Plot1_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color BdGrp_Plot2_color {
            get {
                return ((global::System.Drawing.Color)(this["BdGrp_Plot2_color"]));
            }
            set {
                this["BdGrp_Plot2_color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color RtGrp_Axis_Color {
            get {
                return ((global::System.Drawing.Color)(this["RtGrp_Axis_Color"]));
            }
            set {
                this["RtGrp_Axis_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color NiGrp_Axis_Color {
            get {
                return ((global::System.Drawing.Color)(this["NiGrp_Axis_Color"]));
            }
            set {
                this["NiGrp_Axis_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color BdGrp_Axis_Color {
            get {
                return ((global::System.Drawing.Color)(this["BdGrp_Axis_Color"]));
            }
            set {
                this["BdGrp_Axis_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BdGrp_Backcolor {
            get {
                return ((global::System.Drawing.Color)(this["BdGrp_Backcolor"]));
            }
            set {
                this["BdGrp_Backcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color BdGrp_Grid_Color {
            get {
                return ((global::System.Drawing.Color)(this["BdGrp_Grid_Color"]));
            }
            set {
                this["BdGrp_Grid_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color NiGrp_Grid_Color {
            get {
                return ((global::System.Drawing.Color)(this["NiGrp_Grid_Color"]));
            }
            set {
                this["NiGrp_Grid_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BdGrp_Plot1_Lineview {
            get {
                return ((bool)(this["BdGrp_Plot1_Lineview"]));
            }
            set {
                this["BdGrp_Plot1_Lineview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BdGrp_Plot2_Lineview {
            get {
                return ((bool)(this["BdGrp_Plot2_Lineview"]));
            }
            set {
                this["BdGrp_Plot2_Lineview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NiGrp_Grid_View {
            get {
                return ((bool)(this["NiGrp_Grid_View"]));
            }
            set {
                this["NiGrp_Grid_View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NiGrp_Legend_View {
            get {
                return ((bool)(this["NiGrp_Legend_View"]));
            }
            set {
                this["NiGrp_Legend_View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BdGrp_Legend_View {
            get {
                return ((bool)(this["BdGrp_Legend_View"]));
            }
            set {
                this["BdGrp_Legend_View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BdGrp_Grid_Y1view {
            get {
                return ((bool)(this["BdGrp_Grid_Y1view"]));
            }
            set {
                this["BdGrp_Grid_Y1view"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BdGrp_Grid_Y2view {
            get {
                return ((bool)(this["BdGrp_Grid_Y2view"]));
            }
            set {
                this["BdGrp_Grid_Y2view"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NiGrp_Plot1_Pointview {
            get {
                return ((bool)(this["NiGrp_Plot1_Pointview"]));
            }
            set {
                this["NiGrp_Plot1_Pointview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NiGrp_Plot1_Lineview {
            get {
                return ((bool)(this["NiGrp_Plot1_Lineview"]));
            }
            set {
                this["NiGrp_Plot1_Lineview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BdGrp_Plot1_Pointview {
            get {
                return ((bool)(this["BdGrp_Plot1_Pointview"]));
            }
            set {
                this["BdGrp_Plot1_Pointview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BdGrp_Plot2_Pointview {
            get {
                return ((bool)(this["BdGrp_Plot2_Pointview"]));
            }
            set {
                this["BdGrp_Plot2_Pointview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BdGrp_Plot3_Lineview {
            get {
                return ((bool)(this["BdGrp_Plot3_Lineview"]));
            }
            set {
                this["BdGrp_Plot3_Lineview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BdGrp_Plot3_Pointview {
            get {
                return ((bool)(this["BdGrp_Plot3_Pointview"]));
            }
            set {
                this["BdGrp_Plot3_Pointview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BdGrp_Plot4_Lineview {
            get {
                return ((bool)(this["BdGrp_Plot4_Lineview"]));
            }
            set {
                this["BdGrp_Plot4_Lineview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BdGrp_Plot4_Pointview {
            get {
                return ((bool)(this["BdGrp_Plot4_Pointview"]));
            }
            set {
                this["BdGrp_Plot4_Pointview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NiGrp_Plot2_Lineview {
            get {
                return ((bool)(this["NiGrp_Plot2_Lineview"]));
            }
            set {
                this["NiGrp_Plot2_Lineview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NiGrp_Plot2_Pointview {
            get {
                return ((bool)(this["NiGrp_Plot2_Pointview"]));
            }
            set {
                this["NiGrp_Plot2_Pointview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color RtGrp_GridColor {
            get {
                return ((global::System.Drawing.Color)(this["RtGrp_GridColor"]));
            }
            set {
                this["RtGrp_GridColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RtGrp_GridView {
            get {
                return ((bool)(this["RtGrp_GridView"]));
            }
            set {
                this["RtGrp_GridView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color GrpPlotColor11 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor11"]));
            }
            set {
                this["GrpPlotColor11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color GrpPlotColor12 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor12"]));
            }
            set {
                this["GrpPlotColor12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color GrpPlotColor13 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor13"]));
            }
            set {
                this["GrpPlotColor13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color GrpPlotColor14 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor14"]));
            }
            set {
                this["GrpPlotColor14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Olive")]
        public global::System.Drawing.Color GrpPlotColor15 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor15"]));
            }
            set {
                this["GrpPlotColor15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color GrpPlotColor16 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor16"]));
            }
            set {
                this["GrpPlotColor16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color GrpAxisColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GrpAxisColor1"]));
            }
            set {
                this["GrpAxisColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color GrpGridColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GrpGridColor1"]));
            }
            set {
                this["GrpGridColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GrpBackColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GrpBackColor1"]));
            }
            set {
                this["GrpBackColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color GrpPlotColor21 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor21"]));
            }
            set {
                this["GrpPlotColor21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color GrpPlotColor22 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor22"]));
            }
            set {
                this["GrpPlotColor22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color GrpPlotColor23 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor23"]));
            }
            set {
                this["GrpPlotColor23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color GrpPlotColor24 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor24"]));
            }
            set {
                this["GrpPlotColor24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Olive")]
        public global::System.Drawing.Color GrpPlotColor25 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor25"]));
            }
            set {
                this["GrpPlotColor25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color GrpPlotColor26 {
            get {
                return ((global::System.Drawing.Color)(this["GrpPlotColor26"]));
            }
            set {
                this["GrpPlotColor26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color GrpAxisColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GrpAxisColor2"]));
            }
            set {
                this["GrpAxisColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color GrpGridColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GrpGridColor2"]));
            }
            set {
                this["GrpGridColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GrpBackColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GrpBackColor2"]));
            }
            set {
                this["GrpBackColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine11 {
            get {
                return ((bool)(this["GrpPlotLine11"]));
            }
            set {
                this["GrpPlotLine11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine12 {
            get {
                return ((bool)(this["GrpPlotLine12"]));
            }
            set {
                this["GrpPlotLine12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine13 {
            get {
                return ((bool)(this["GrpPlotLine13"]));
            }
            set {
                this["GrpPlotLine13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine14 {
            get {
                return ((bool)(this["GrpPlotLine14"]));
            }
            set {
                this["GrpPlotLine14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine15 {
            get {
                return ((bool)(this["GrpPlotLine15"]));
            }
            set {
                this["GrpPlotLine15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine16 {
            get {
                return ((bool)(this["GrpPlotLine16"]));
            }
            set {
                this["GrpPlotLine16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint11 {
            get {
                return ((bool)(this["GrpPlotPoint11"]));
            }
            set {
                this["GrpPlotPoint11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint12 {
            get {
                return ((bool)(this["GrpPlotPoint12"]));
            }
            set {
                this["GrpPlotPoint12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint13 {
            get {
                return ((bool)(this["GrpPlotPoint13"]));
            }
            set {
                this["GrpPlotPoint13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint14 {
            get {
                return ((bool)(this["GrpPlotPoint14"]));
            }
            set {
                this["GrpPlotPoint14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint15 {
            get {
                return ((bool)(this["GrpPlotPoint15"]));
            }
            set {
                this["GrpPlotPoint15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint16 {
            get {
                return ((bool)(this["GrpPlotPoint16"]));
            }
            set {
                this["GrpPlotPoint16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine21 {
            get {
                return ((bool)(this["GrpPlotLine21"]));
            }
            set {
                this["GrpPlotLine21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine22 {
            get {
                return ((bool)(this["GrpPlotLine22"]));
            }
            set {
                this["GrpPlotLine22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine23 {
            get {
                return ((bool)(this["GrpPlotLine23"]));
            }
            set {
                this["GrpPlotLine23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine24 {
            get {
                return ((bool)(this["GrpPlotLine24"]));
            }
            set {
                this["GrpPlotLine24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine25 {
            get {
                return ((bool)(this["GrpPlotLine25"]));
            }
            set {
                this["GrpPlotLine25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotLine26 {
            get {
                return ((bool)(this["GrpPlotLine26"]));
            }
            set {
                this["GrpPlotLine26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint21 {
            get {
                return ((bool)(this["GrpPlotPoint21"]));
            }
            set {
                this["GrpPlotPoint21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint22 {
            get {
                return ((bool)(this["GrpPlotPoint22"]));
            }
            set {
                this["GrpPlotPoint22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint23 {
            get {
                return ((bool)(this["GrpPlotPoint23"]));
            }
            set {
                this["GrpPlotPoint23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint24 {
            get {
                return ((bool)(this["GrpPlotPoint24"]));
            }
            set {
                this["GrpPlotPoint24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint25 {
            get {
                return ((bool)(this["GrpPlotPoint25"]));
            }
            set {
                this["GrpPlotPoint25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpPlotPoint26 {
            get {
                return ((bool)(this["GrpPlotPoint26"]));
            }
            set {
                this["GrpPlotPoint26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrpAxisGridY11 {
            get {
                return ((bool)(this["GrpAxisGridY11"]));
            }
            set {
                this["GrpAxisGridY11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrpAxisGridY12 {
            get {
                return ((bool)(this["GrpAxisGridY12"]));
            }
            set {
                this["GrpAxisGridY12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrpAxisGridY21 {
            get {
                return ((bool)(this["GrpAxisGridY21"]));
            }
            set {
                this["GrpAxisGridY21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrpAxisGridY22 {
            get {
                return ((bool)(this["GrpAxisGridY22"]));
            }
            set {
                this["GrpAxisGridY22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrpAxisGridX1 {
            get {
                return ((bool)(this["GrpAxisGridX1"]));
            }
            set {
                this["GrpAxisGridX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrpAxisGridX2 {
            get {
                return ((bool)(this["GrpAxisGridX2"]));
            }
            set {
                this["GrpAxisGridX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpViewLegend1 {
            get {
                return ((bool)(this["GrpViewLegend1"]));
            }
            set {
                this["GrpViewLegend1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrpViewLegend2 {
            get {
                return ((bool)(this["GrpViewLegend2"]));
            }
            set {
                this["GrpViewLegend2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MaxWinCh {
            get {
                return ((int)(this["MaxWinCh"]));
            }
            set {
                this["MaxWinCh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int GrpMaxWinCh {
            get {
                return ((int)(this["GrpMaxWinCh"]));
            }
            set {
                this["GrpMaxWinCh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RtGrpLegendView {
            get {
                return ((bool)(this["RtGrpLegendView"]));
            }
            set {
                this["RtGrpLegendView"] = value;
            }
        }
    }
}
