####---- CreateClock list ----6
create_clock  -period 1000.00 -waveform {0.00 500.00} -name {zim|TEST_LED} [get_nets {TEST_LED}] 
create_clock  -period 1000.00 -waveform {0.00 500.00} -name {zim|VDC_CLK} [get_nets {VDC_CLK}] 
create_clock  -period 1000.00 -waveform {0.00 500.00} -name {zim|clk_32MHz} [get_nets {clk_32MHz}] 
create_clock  -period 1000.00 -waveform {0.00 500.00} -name {zim|clk_16MHz} [get_nets {clk_16MHz}] 
create_clock  -period 1000.00 -waveform {0.00 500.00} -name {zim|clk_RTD} [get_nets {clk_RTD}] 
create_clock  -period 1000.00 -waveform {0.00 500.00} -name {zim|\comm_spi/iclk} [get_nets {comm_spi.iclk}] 

####---- SetFalsePath list ----30
set_false_path  -from [get_clocks {zim|\comm_spi/iclk}]  -to [get_clocks {zim|clk_32MHz}]
set_false_path  -from [get_clocks {zim|clk_32MHz}]  -to [get_clocks {zim|clk_RTD}]
set_false_path  -from [get_clocks {zim|TEST_LED}]  -to [get_clocks {zim|clk_32MHz}]
set_false_path  -from [get_clocks {zim|TEST_LED}]  -to [get_clocks {zim|VDC_CLK}]
set_false_path  -from [get_clocks {zim|\comm_spi/iclk}]  -to [get_clocks {zim|clk_16MHz}]
set_false_path  -from [get_clocks {zim|clk_RTD}]  -to [get_clocks {zim|TEST_LED}]
set_false_path  -from [get_clocks {zim|VDC_CLK}]  -to [get_clocks {zim|clk_32MHz}]
set_false_path  -from [get_clocks {zim|TEST_LED}]  -to [get_clocks {zim|\comm_spi/iclk}]
set_false_path  -from [get_clocks {zim|\comm_spi/iclk}]  -to [get_clocks {zim|VDC_CLK}]
set_false_path  -from [get_clocks {zim|clk_16MHz}]  -to [get_clocks {zim|clk_RTD}]
set_false_path  -from [get_clocks {zim|clk_32MHz}]  -to [get_clocks {zim|\comm_spi/iclk}]
set_false_path  -from [get_clocks {zim|VDC_CLK}]  -to [get_clocks {zim|clk_RTD}]
set_false_path  -from [get_clocks {zim|\comm_spi/iclk}]  -to [get_clocks {zim|TEST_LED}]
set_false_path  -from [get_clocks {zim|clk_16MHz}]  -to [get_clocks {zim|clk_32MHz}]
set_false_path  -from [get_clocks {zim|clk_32MHz}]  -to [get_clocks {zim|clk_16MHz}]
set_false_path  -from [get_clocks {zim|VDC_CLK}]  -to [get_clocks {zim|\comm_spi/iclk}]
set_false_path  -from [get_clocks {zim|clk_16MHz}]  -to [get_clocks {zim|\comm_spi/iclk}]
set_false_path  -from [get_clocks {zim|clk_32MHz}]  -to [get_clocks {zim|TEST_LED}]
set_false_path  -from [get_clocks {zim|clk_RTD}]  -to [get_clocks {zim|clk_16MHz}]
set_false_path  -from [get_clocks {zim|VDC_CLK}]  -to [get_clocks {zim|clk_16MHz}]
set_false_path  -from [get_clocks {zim|clk_16MHz}]  -to [get_clocks {zim|VDC_CLK}]
set_false_path  -from [get_clocks {zim|clk_32MHz}]  -to [get_clocks {zim|VDC_CLK}]
set_false_path  -from [get_clocks {zim|clk_RTD}]  -to [get_clocks {zim|clk_32MHz}]
set_false_path  -from [get_clocks {zim|TEST_LED}]  -to [get_clocks {zim|clk_RTD}]
set_false_path  -from [get_clocks {zim|clk_16MHz}]  -to [get_clocks {zim|TEST_LED}]
set_false_path  -from [get_clocks {zim|clk_RTD}]  -to [get_clocks {zim|VDC_CLK}]
set_false_path  -from [get_clocks {zim|VDC_CLK}]  -to [get_clocks {zim|TEST_LED}]
set_false_path  -from [get_clocks {zim|\comm_spi/iclk}]  -to [get_clocks {zim|clk_RTD}]
set_false_path  -from [get_clocks {zim|TEST_LED}]  -to [get_clocks {zim|clk_16MHz}]
set_false_path  -from [get_clocks {zim|clk_RTD}]  -to [get_clocks {zim|\comm_spi/iclk}]

