//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiveLab.ZM.Dataview.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZiveLab.ZM.Dataview.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   |Q|({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AbsQ_x {
            get {
                return ResourceManager.GetString("AbsQ_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acc. E(Wh)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Acc_d_E_Wh {
            get {
                return ResourceManager.GetString("Acc_d_E_Wh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acc. Q({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Acc_d_Q_x {
            get {
                return ResourceManager.GetString("Acc_d_Q_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Acc. Q({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Acc_d_Qx {
            get {
                return ResourceManager.GetString("Acc_d_Qx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accumulate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Accumulate {
            get {
                return ResourceManager.GetString("Accumulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accumulate Q과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Accumulate_Q {
            get {
                return ResourceManager.GetString("Accumulate_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accumulate Wh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Accumulate_Wh {
            get {
                return ResourceManager.GetString("Accumulate_Wh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Area({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Active_Area_Unit {
            get {
                return ResourceManager.GetString("Active_Area_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active_Area({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Active_Area_x {
            get {
                return ResourceManager.GetString("Active_Area_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACV Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACVGraph {
            get {
                return ResourceManager.GetString("ACVGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Data Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Add_Data_Files {
            get {
                return ResourceManager.GetString("Add_Data_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Data Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Add_Data_Folder {
            get {
                return ResourceManager.GetString("Add_Data_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string All_Files {
            get {
                return ResourceManager.GetString("All_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyzing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Analyzing {
            get {
                return ResourceManager.GetString("Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Application_Version {
            get {
                return ResourceManager.GetString("Application_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascii File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ascii_File {
            get {
                return ResourceManager.GetString("Ascii_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascii Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ascii_Files {
            get {
                return ResourceManager.GetString("Ascii_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascii (txt , csv)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ascii_txt_csv {
            get {
                return ResourceManager.GetString("Ascii_txt_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux1 {
            get {
                return ResourceManager.GetString("Aux1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux10과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux10 {
            get {
                return ResourceManager.GetString("Aux10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux10과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux101 {
            get {
                return ResourceManager.GetString("Aux101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux11과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux11 {
            get {
                return ResourceManager.GetString("Aux11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux11과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux111 {
            get {
                return ResourceManager.GetString("Aux111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux12과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux12 {
            get {
                return ResourceManager.GetString("Aux12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux12과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux121 {
            get {
                return ResourceManager.GetString("Aux121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux13 {
            get {
                return ResourceManager.GetString("Aux13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux2 {
            get {
                return ResourceManager.GetString("Aux2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux21 {
            get {
                return ResourceManager.GetString("Aux21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux3 {
            get {
                return ResourceManager.GetString("Aux3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux31 {
            get {
                return ResourceManager.GetString("Aux31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux4 {
            get {
                return ResourceManager.GetString("Aux4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux41 {
            get {
                return ResourceManager.GetString("Aux41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux5 {
            get {
                return ResourceManager.GetString("Aux5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux51 {
            get {
                return ResourceManager.GetString("Aux51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux6 {
            get {
                return ResourceManager.GetString("Aux6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux61 {
            get {
                return ResourceManager.GetString("Aux61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux7과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux7 {
            get {
                return ResourceManager.GetString("Aux7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux7과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux71 {
            get {
                return ResourceManager.GetString("Aux71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux8 {
            get {
                return ResourceManager.GetString("Aux8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux81 {
            get {
                return ResourceManager.GetString("Aux81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux9과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux9 {
            get {
                return ResourceManager.GetString("Aux9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux9과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Aux91 {
            get {
                return ResourceManager.GetString("Aux91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux Board과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AuxBoardInfo {
            get {
                return ResourceManager.GetString("AuxBoardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auxiliary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Auxiliary {
            get {
                return ResourceManager.GetString("Auxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auxiliary(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Auxiliary_V {
            get {
                return ResourceManager.GetString("Auxiliary_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aux{0}(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AuxX_V {
            get {
                return ResourceManager.GetString("AuxX_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average V Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Average_V_Graph {
            get {
                return ResourceManager.GetString("Average_V_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Axis-X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Axis_d_X {
            get {
                return ResourceManager.GetString("Axis_d_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Axis-Y{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Axis_d_Yx {
            get {
                return ResourceManager.GetString("Axis_d_Yx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BatteryId {
            get {
                return ResourceManager.GetString("BatteryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bode Plot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Bode_Graph {
            get {
                return ResourceManager.GetString("Bode_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BZA&apos;s data files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BZADataFiles {
            get {
                return ResourceManager.GetString("BZADataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capacity({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Capacity_Unit {
            get {
                return ResourceManager.GetString("Capacity_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capacity({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Capacity_x {
            get {
                return ResourceManager.GetString("Capacity_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cell Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CellType {
            get {
                return ResourceManager.GetString("CellType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ch Q/NQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ch_Q_NQ {
            get {
                return ResourceManager.GetString("Ch_Q_NQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ch Q/Q1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ch_Q_Q1 {
            get {
                return ResourceManager.GetString("Ch_Q_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change capacity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Change_Capacity {
            get {
                return ResourceManager.GetString("Change_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charge P과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Charge_P {
            get {
                return ResourceManager.GetString("Charge_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charge Q과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Charge_Q {
            get {
                return ResourceManager.GetString("Charge_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Charge Wh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Charge_Wh {
            get {
                return ResourceManager.GetString("Charge_Wh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chg.E(Wh)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chg_d_E_Wh {
            get {
                return ResourceManager.GetString("Chg_d_E_Wh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chg.LastV(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chg_d_LastV_V {
            get {
                return ResourceManager.GetString("Chg_d_LastV_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chg.Q_s({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chg_d_Q_sx {
            get {
                return ResourceManager.GetString("Chg_d_Q_sx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chg.Q({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chg_d_Qx {
            get {
                return ResourceManager.GetString("Chg_d_Qx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chg. Vavg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Chg_d_Vavg {
            get {
                return ResourceManager.GetString("Chg_d_Vavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChInfo {
            get {
                return ResourceManager.GetString("ChInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comma과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert To Ascii File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Convert_To_Ascii_File {
            get {
                return ResourceManager.GetString("Convert_To_Ascii_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert To Excel File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Convert_To_Excel_File {
            get {
                return ResourceManager.GetString("Convert_To_Excel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Converting_ddd {
            get {
                return ResourceManager.GetString("Converting_ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Graph Image To Clipboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Copy_Graph_Image_To_Clipboard {
            get {
                return ResourceManager.GetString("Copy_Graph_Image_To_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coulomb Eff.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Coulomb_Eff_d {
            get {
                return ResourceManager.GetString("Coulomb_Eff_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coulomb Eff.(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Coulomb_Eff_d_p {
            get {
                return ResourceManager.GetString("Coulomb_Eff_d_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cs/Cp vs Time Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cs_Cp_vs_TimeGraph {
            get {
                return ResourceManager.GetString("Cs_Cp_vs_TimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current(A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Current_A {
            get {
                return ResourceManager.GetString("Current_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Current_Range {
            get {
                return ResourceManager.GetString("Current_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current vs Voltage Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Current_vs_Voltage_Graph {
            get {
                return ResourceManager.GetString("Current_vs_Voltage_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cursor On/Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cursor_On_s_Off {
            get {
                return ResourceManager.GetString("Cursor_On_s_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cyc_Time {
            get {
                return ResourceManager.GetString("Cyc_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cycle_Data {
            get {
                return ResourceManager.GetString("Cycle_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle Data Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cycle_Data_Report {
            get {
                return ResourceManager.GetString("Cycle_Data_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cycle_No_d {
            get {
                return ResourceManager.GetString("Cycle_No_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle Range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cycle_Range {
            get {
                return ResourceManager.GetString("Cycle_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cycle Time(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cycle_Time_s {
            get {
                return ResourceManager.GetString("Cycle_Time_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Data_Count {
            get {
                return ResourceManager.GetString("Data_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data File Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Data_File_Version {
            get {
                return ResourceManager.GetString("Data_File_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Data_Files {
            get {
                return ResourceManager.GetString("Data_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Data_Report {
            get {
                return ResourceManager.GetString("Data_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Data_Type {
            get {
                return ResourceManager.GetString("Data_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dch Q/NQ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dch_Q_NQ {
            get {
                return ResourceManager.GetString("Dch_Q_NQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dch Q/Q1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dch_Q_Q1 {
            get {
                return ResourceManager.GetString("Dch_Q_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dchg. Vavg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dchg_d_Vavg {
            get {
                return ResourceManager.GetString("Dchg_d_Vavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delimiter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Density Mode - Change Active Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Density_Mode_a_Change_Active_Area {
            get {
                return ResourceManager.GetString("Density_Mode_a_Change_Active_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Device_Type {
            get {
                return ResourceManager.GetString("Device_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Direction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharge P과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Discharge_P {
            get {
                return ResourceManager.GetString("Discharge_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharge Q과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Discharge_Q {
            get {
                return ResourceManager.GetString("Discharge_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discharge Wh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Discharge_Wh {
            get {
                return ResourceManager.GetString("Discharge_Wh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dischg.E(Wh)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dischg_d_E_Wh {
            get {
                return ResourceManager.GetString("Dischg_d_E_Wh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dischg.LastV(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dischg_d_LastV_V {
            get {
                return ResourceManager.GetString("Dischg_d_LastV_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dischg.Q_s({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dischg_d_Q_sx {
            get {
                return ResourceManager.GetString("Dischg_d_Q_sx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dischg.Q({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dischg_d_Qx {
            get {
                return ResourceManager.GetString("Dischg_d_Qx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Division과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EIS Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EIS_Data {
            get {
                return ResourceManager.GetString("EIS_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EIS Data Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EIS_Data_Report {
            get {
                return ResourceManager.GetString("EIS_Data_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Elapsed_Time {
            get {
                return ResourceManager.GetString("Elapsed_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restoring is over.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EndRestore {
            get {
                return ResourceManager.GetString("EndRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Energy Eff.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Energy_Eff_d {
            get {
                return ResourceManager.GetString("Energy_Eff_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Energy Eff.(%)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Energy_Eff_d_p {
            get {
                return ResourceManager.GetString("Energy_Eff_d_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eoc/Temperature vs Time Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Eoc_Temp_vs_TimeGraph {
            get {
                return ResourceManager.GetString("Eoc_Temp_vs_TimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eoc(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Eoc_V {
            get {
                return ResourceManager.GetString("Eoc_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eref/I vs Time Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Eref_s_I_vs_Time_Graph {
            get {
                return ResourceManager.GetString("Eref_s_I_vs_Time_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eref vs |Q| Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Eref_vs_AbsQ_Graph {
            get {
                return ResourceManager.GetString("Eref_vs_AbsQ_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error : Open failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_c_Open_failed {
            get {
                return ResourceManager.GetString("Error_c_Open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error : Unsupported file format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_c_Unsupported_file_format {
            get {
                return ResourceManager.GetString("Error_c_Unsupported_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Code : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Code_x {
            get {
                return ResourceManager.GetString("Error_Code_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Excel_Files {
            get {
                return ResourceManager.GetString("Excel_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel 97-2003 Workbook (xls)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Excel_Old_xls {
            get {
                return ResourceManager.GetString("Excel_Old_xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Workbook (xlsx)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Excel_Workbook_xlsx {
            get {
                return ResourceManager.GetString("Excel_Workbook_xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed File Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Failed_File_Open {
            get {
                return ResourceManager.GetString("Failed_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File creation failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_creation_failed {
            get {
                return ResourceManager.GetString("File_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Index과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Index {
            get {
                return ResourceManager.GetString("File_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data File Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Information {
            get {
                return ResourceManager.GetString("File_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_No_d {
            get {
                return ResourceManager.GetString("File_No_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Time {
            get {
                return ResourceManager.GetString("File_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Time(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string File_Time_s {
            get {
                return ResourceManager.GetString("File_Time_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap fileinfor {
            get {
                object obj = ResourceManager.GetObject("fileinfor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   The restore operation has been completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FinishRestore {
            get {
                return ResourceManager.GetString("FinishRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firmware_Version {
            get {
                return ResourceManager.GetString("Firmware_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frequency(Hz)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frequency_Hz {
            get {
                return ResourceManager.GetString("Frequency_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string General_Data {
            get {
                return ResourceManager.GetString("General_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Data Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string General_Data_Report {
            get {
                return ResourceManager.GetString("General_Data_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GeneralGraph {
            get {
                return ResourceManager.GetString("GeneralGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graph Axes and Data Filter Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Graph_Axes_and_Data_Filter_Setting {
            get {
                return ResourceManager.GetString("Graph_Axes_and_Data_Filter_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid On/Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Grid_On_s_Off {
            get {
                return ResourceManager.GetString("Grid_On_s_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idc(A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Idc_A {
            get {
                return ResourceManager.GetString("Idc_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDLE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IDLE {
            get {
                return ResourceManager.GetString("IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize Graph to Original과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Initialize_Graph_to_Original {
            get {
                return ResourceManager.GetString("Initialize_Graph_to_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR(ohm)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IR_ohm {
            get {
                return ResourceManager.GetString("IR_ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon ivex {
            get {
                object obj = ResourceManager.GetObject("ivex", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ivman {
            get {
                object obj = ResourceManager.GetObject("ivman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ivmandiff {
            get {
                object obj = ResourceManager.GetObject("ivmandiff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ivmansolar {
            get {
                object obj = ResourceManager.GetObject("ivmansolar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ivmantafel {
            get {
                object obj = ResourceManager.GetObject("ivmantafel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Korean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legend과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legend On/Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Legend_On_s_Off {
            get {
                return ResourceManager.GetString("Legend_On_s_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line On/Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Line_On_s_Off {
            get {
                return ResourceManager.GetString("Line_On_s_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load(Ω)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Load_ohm {
            get {
                return ResourceManager.GetString("Load_ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loaded과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loading_ddd {
            get {
                return ResourceManager.GetString("Loading_ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log I과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log_I {
            get {
                return ResourceManager.GetString("Log_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logarithm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Logarithm {
            get {
                return ResourceManager.GetString("Logarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Major Grid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Major_Grid {
            get {
                return ResourceManager.GetString("Major_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. V과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Max_d_V {
            get {
                return ResourceManager.GetString("Max_d_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. V(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Max_d_V_V {
            get {
                return ResourceManager.GetString("Max_d_V_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min. V과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Min_d_V {
            get {
                return ResourceManager.GetString("Min_d_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minor Grid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Minor_Grid {
            get {
                return ResourceManager.GetString("Minor_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Model_Name {
            get {
                return ResourceManager.GetString("Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Ascii file conversion is complete. Do you want to open the file?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_AsciiConvOk {
            get {
                return ResourceManager.GetString("Msg_AsciiConvOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot open schedule file!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_CannotOpenSchFile {
            get {
                return ResourceManager.GetString("Msg_CannotOpenSchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete selected row(s)?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_DelSelRow_Q {
            get {
                return ResourceManager.GetString("Msg_DelSelRow_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exceeds the number of open files.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_ExceedsOpenFiles {
            get {
                return ResourceManager.GetString("Msg_ExceedsOpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Excel file conversion is complete. Do you want to open the file?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_ExcelConvOk {
            get {
                return ResourceManager.GetString("Msg_ExcelConvOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is being converted. Are you sure you want to terminate?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_InConverting {
            get {
                return ResourceManager.GetString("Msg_InConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It contains a character that can not use the file name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_InvalidFileName {
            get {
                return ResourceManager.GetString("Msg_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schedule information is not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_NoSchInfor {
            get {
                return ResourceManager.GetString("Msg_NoSchInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to open the saved file in another Data Editor?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_OpenNewDataEditor {
            get {
                return ResourceManager.GetString("Msg_OpenNewDataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It has the same destination file in the list. Please check.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SameFile {
            get {
                return ResourceManager.GetString("Msg_SameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the source file first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SpecifySrcFile {
            get {
                return ResourceManager.GetString("Msg_SpecifySrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you also want to add files in subfolders?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MsgAddSubDir {
            get {
                return ResourceManager.GetString("MsgAddSubDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Batch Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No_BatchData {
            get {
                return ResourceManager.GetString("No_BatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nyquist Plot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Nyquist_Graph {
            get {
                return ResourceManager.GetString("Nyquist_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OCP(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OCP_V {
            get {
                return ResourceManager.GetString("OCP_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Data Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open_Data_Editor {
            get {
                return ResourceManager.GetString("Open_Data_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Data File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open_Data_File {
            get {
                return ResourceManager.GetString("Open_Data_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap open_folder {
            get {
                object obj = ResourceManager.GetObject("open_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Open Schedule Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open_Schedule_Editor {
            get {
                return ResourceManager.GetString("Open_Schedule_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Schedule File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Open_Schedule_File {
            get {
                return ResourceManager.GetString("Open_Schedule_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open SI Data file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenSIDataFile {
            get {
                return ResourceManager.GetString("OpenSIDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open SM Data File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenSMDataFile {
            get {
                return ResourceManager.GetString("OpenSMDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Order_Number {
            get {
                return ResourceManager.GetString("Order_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pan Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pan_Mode {
            get {
                return ResourceManager.GetString("Pan_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap pd1 {
            get {
                object obj = ResourceManager.GetObject("pd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap pfm {
            get {
                object obj = ResourceManager.GetObject("pfm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Plot Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plot_Area {
            get {
                return ResourceManager.GetString("Plot_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point On/Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Point_On_s_Off {
            get {
                return ResourceManager.GetString("Point_On_s_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power(W)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Power_W {
            get {
                return ResourceManager.GetString("Power_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Print_Data {
            get {
                return ResourceManager.GetString("Print_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Print_Graph {
            get {
                return ResourceManager.GetString("Print_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Battery ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Product_No_d {
            get {
                return ResourceManager.GetString("Product_No_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Q {
            get {
                return ResourceManager.GetString("Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q vs CycleN Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Q_vs_CycleN_Graph {
            get {
                return ResourceManager.GetString("Q_vs_CycleN_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reading_ddd {
            get {
                return ResourceManager.GetString("Reading_ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redraw과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Redraw {
            get {
                return ResourceManager.GetString("Redraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload Data File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reload_Data_File {
            get {
                return ResourceManager.GetString("Reload_Data_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload Graph From File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reload_Graph_From_File {
            get {
                return ResourceManager.GetString("Reload_Graph_From_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Selected Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Remove_Selected_Item {
            get {
                return ResourceManager.GetString("Remove_Selected_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resampling...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Resampling_ddd {
            get {
                return ResourceManager.GetString("Resampling_ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Restoring {
            get {
                return ResourceManager.GetString("Restoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Result_File {
            get {
                return ResourceManager.GetString("Result_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rs/Cs vs Frequency Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RsCs_vs_Freq_Graph {
            get {
                return ResourceManager.GetString("RsCs_vs_Freq_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_File_Explorer {
            get {
                return ResourceManager.GetString("Run_File_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run IVMAN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_IVMAN {
            get {
                return ResourceManager.GetString("Run_IVMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run IVMAN Differential Analysis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_IVMAN_Differential_Analysis {
            get {
                return ResourceManager.GetString("Run_IVMAN_Differential_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run IVMAN Extractor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_IVMan_Extractor {
            get {
                return ResourceManager.GetString("Run_IVMan_Extractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run IVMan Peak Find Module과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_IVMan_Peak_Find_Module {
            get {
                return ResourceManager.GetString("Run_IVMan_Peak_Find_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run IVMAN Photovoltaic-Cell Analysis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_IVMAN_Photovoltaic_a_Cell_Analysis {
            get {
                return ResourceManager.GetString("Run_IVMAN_Photovoltaic_a_Cell_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run IVMan Tafel Analysis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_IVMan_Tafel_Analysis {
            get {
                return ResourceManager.GetString("Run_IVMan_Tafel_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run Peak Detector...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_Peak_Detector {
            get {
                return ResourceManager.GetString("Run_Peak_Detector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run ZMAN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Run_ZMan {
            get {
                return ResourceManager.GetString("Run_ZMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As Data File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save_As_Data_File {
            get {
                return ResourceManager.GetString("Save_As_Data_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Ascii File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save_Ascii_File {
            get {
                return ResourceManager.GetString("Save_Ascii_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save_Error {
            get {
                return ResourceManager.GetString("Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Excel File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save_Excel_File {
            get {
                return ResourceManager.GetString("Save_Excel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Saving_ddd {
            get {
                return ResourceManager.GetString("Saving_ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScaleType과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ScaleType {
            get {
                return ResourceManager.GetString("ScaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schedule File Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Schedule_File_Name {
            get {
                return ResourceManager.GetString("Schedule_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search voltage value at % capacity per cycle.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchVatSpecificCap {
            get {
                return ResourceManager.GetString("SearchVatSpecificCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_All_Items {
            get {
                return ResourceManager.GetString("Select_All_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Current Density과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_Current_Density {
            get {
                return ResourceManager.GetString("Select_Current_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Normal Current과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_Normal_Current {
            get {
                return ResourceManager.GetString("Select_Normal_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Specific Current과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_Specific_Current {
            get {
                return ResourceManager.GetString("Select_Specific_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Serial_Number {
            get {
                return ResourceManager.GetString("Serial_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SIF Firmware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SIF_Firmware {
            get {
                return ResourceManager.GetString("SIF_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SIF Serial과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SIF_Serial {
            get {
                return ResourceManager.GetString("SIF_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SIF Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SIF_Version {
            get {
                return ResourceManager.GetString("SIF_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SIF Board과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SIFInfo {
            get {
                return ResourceManager.GetString("SIFInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source Data File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Source_Data_File {
            get {
                return ResourceManager.GetString("Source_Data_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Space과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specific Mode - Change Weight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Specific_Mode_a_Change_Weight {
            get {
                return ResourceManager.GetString("Specific_Mode_a_Change_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Splitting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Splitting_ddd {
            get {
                return ResourceManager.GetString("Splitting_ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Start_Convert {
            get {
                return ResourceManager.GetString("Start_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Step_Count {
            get {
                return ResourceManager.GetString("Step_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Step_No_d {
            get {
                return ResourceManager.GetString("Step_No_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Step_Time {
            get {
                return ResourceManager.GetString("Step_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Step Time(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Step_Time_s {
            get {
                return ResourceManager.GetString("Step_Time_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Convert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stop_Convert {
            get {
                return ResourceManager.GetString("Stop_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Loading과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stop_Loading {
            get {
                return ResourceManager.GetString("Stop_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tech. File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tech_File {
            get {
                return ResourceManager.GetString("Tech_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp.(&apos;C)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Temp_d_C {
            get {
                return ResourceManager.GetString("Temp_d_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Data File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Test_Data_File {
            get {
                return ResourceManager.GetString("Test_Data_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Duration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Test_Duration {
            get {
                return ResourceManager.GetString("Test_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Test_LastStatus {
            get {
                return ResourceManager.GetString("Test_LastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Test_PausedTime {
            get {
                return ResourceManager.GetString("Test_PausedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Test_Time {
            get {
                return ResourceManager.GetString("Test_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Time(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Test_Time_s {
            get {
                return ResourceManager.GetString("Test_Time_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tester과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tester {
            get {
                return ResourceManager.GetString("Tester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uncheck All Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uncheck_All_Items {
            get {
                return ResourceManager.GetString("Uncheck_All_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unload Selected File on Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Unload_Selected_File_on_Graph {
            get {
                return ResourceManager.GetString("Unload_Selected_File_on_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported File Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Unsupported_File_Format {
            get {
                return ResourceManager.GetString("Unsupported_File_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string User_Stop {
            get {
                return ResourceManager.GetString("User_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vavg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Vavg {
            get {
                return ResourceManager.GetString("Vavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vdc/Temperature vs Time Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Vdc_Temp_vs_TimeGraph {
            get {
                return ResourceManager.GetString("Vdc_Temp_vs_TimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vdc(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Vdc_V {
            get {
                return ResourceManager.GetString("Vdc_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Cycle Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string View_Cycle_Graph {
            get {
                return ResourceManager.GetString("View_Cycle_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View General Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string View_General_Graph {
            get {
                return ResourceManager.GetString("View_General_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View/Hide REST Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string View_s_Hide_REST_Data {
            get {
                return ResourceManager.GetString("View_s_Hide_REST_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage(V)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Voltage_V {
            get {
                return ResourceManager.GetString("Voltage_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voltage vs LogI Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Voltage_vs_LogI_Graph {
            get {
                return ResourceManager.GetString("Voltage_vs_LogI_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Waiting_ddd {
            get {
                return ResourceManager.GetString("Waiting_ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weight(g)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Weight_g_ {
            get {
                return ResourceManager.GetString("Weight_g_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Write_failed {
            get {
                return ResourceManager.GetString("Write_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X Axis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X_Axis {
            get {
                return ResourceManager.GetString("X_Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y{0} Axis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Yx_Axis {
            get {
                return ResourceManager.GetString("Yx_Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIM Board과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZIM_Board {
            get {
                return ResourceManager.GetString("ZIM_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIM Firmware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZIM_Firmware {
            get {
                return ResourceManager.GetString("ZIM_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zim(ohm)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Zim_ohm {
            get {
                return ResourceManager.GetString("Zim_ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIM Serial과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZIM_Serial {
            get {
                return ResourceManager.GetString("ZIM_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zmag(ohm)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Zmag_ohm {
            get {
                return ResourceManager.GetString("Zmag_ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Zoom_Mode {
            get {
                return ResourceManager.GetString("Zoom_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZPhase(deg)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ZPhase_deg {
            get {
                return ResourceManager.GetString("ZPhase_deg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zre(ohm)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Zre_ohm {
            get {
                return ResourceManager.GetString("Zre_ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zre/Vdc vs Time Graph과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Zre_Vdc_vs_TimeGraph {
            get {
                return ResourceManager.GetString("Zre_Vdc_vs_TimeGraph", resourceCulture);
            }
        }
    }
}
